export { default as User } from './User';
export { default as Attendance } from './Attendance';
export { default as Mark } from './Mark';
export { default as Doubt } from './Doubt';
export { default as ChatMessage } from './ChatMessage';
export { default as Notification } from './Notification';
export { default as LibraryResource } from './LibraryResource';
export { default as Material } from './Material';
export { default as University } from './University';
export { default as College } from './College';
export { default as Department } from './Department';
export { default as Subject } from './Subject';
export { default as Batch } from './Batch';

export type { IUser } from './User';
export type { IAttendance } from './Attendance';
export type { IMark } from './Mark';
export type { IDoubt } from './Doubt';
export type { IChatMessage } from './ChatMessage';
export type { INotification } from './Notification';
export type { ILibraryResource } from './LibraryResource';
export type { IMaterial } from './Material';
export type { IUniversity } from './University';
export type { ICollege } from './College';
export type { IDepartment } from './Department';
export type { ISubject } from './Subject';
export type { IBatch } from './Batch';
